import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  header: {
    backgroundColor: '#54C1DD',
    paddingTop: 52,
    paddingBottom: 60,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  nav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 16,
  },
  navTitle: { fontSize: 17, fontWeight: '600', color: '#fff' },
  coursePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 16,
    marginBottom: 20,
    maxWidth: '90%',
  },
  coursePillText: { fontSize: 12, color: '#fff', fontWeight: '500', flexShrink: 1 },
  dropdown: {
    position: 'absolute',
    top: 160,
    alignSelf: 'center',
    width: '80%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    backgroundColor: '#54C1DD',
    zIndex: 999,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  dropdownBorder: { borderBottomWidth: 0.5, borderBottomColor: 'rgba(255,255,255,0.3)' },
  dropdownText: { fontSize: 13, color: 'rgba(255,255,255,0.8)', flex: 1 },
  dropdownTextActive: { color: '#fff', fontWeight: '700' },
  ringWrap: { alignItems: 'center', justifyContent: 'center' },
  ringCenter: { position: 'absolute', alignItems: 'center' },
  ringValue: { fontSize: 32, fontWeight: '700', color: '#fff' },
  ringTotal: { fontSize: 13, color: 'rgba(255,255,255,0.75)', marginTop: 2 },
});
